### ISSUE TITLE
 module 'nets.resnet' has no attribute 'resnet18'

### ISSUE THREAD

**Issue by guozijian8** [sparsifai/edropout#2]
Traceback (most recent call last):
  File "edropout.py", line 998, in <module>
    train_ising(args,pretrained_name,pretrained_name_save,stopcounter,input_size, n_classes,s_input_channel,nnmodel,threshold_early_state,ts,loss_func)
  File "edropout.py", line 503, in train_ising
    model = model_select(nnmodel,device,s_input_channel,n_classes)
  File "edropout.py", line 385, in model_select
    model = resnet.resnet18(s_input_channel,n_classes).to(device)
AttributeError: module 'nets.resnet' has no attribute 'resnet18'

**Comment by sparsifai** [comment]
please import realresnet.py instead of resnet.py.
